gui:
  theme:
    activeBorderColor:
      - red
      - bold
    inactiveBorderColor:
      - "#5f5a5a"
      - bold
    selectedLineBgColor:
      - "#3f3a3a"
      - bold
  nerdFontsVersion: "3"
  showDivergenceFromBaseBranch: arrowAndNumber
  border: rounded
  tabWidth: 2
  expandFocusedSidePanel: true
  spinner:
    frames:
      - '󰪞'
      - '󰪟'
      - '󰪠'
      - '󰪡'
      - '󰪢'
      - '󰪣'
      - '󰪤'
      - '󰪥'
    rate: 25

update:
  method: never

git:
  paging:
    pager: "DELTA_FEATURES=lazygit delta --dark --paging=never"
